# Dependabot config reference
# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    -   package-ecosystem: github-actions
        directory: /
        schedule:
            interval: monthly
        groups:
            github-actions: { patterns: ['*'] }
