setup: true
debug: false
instname: null
server: http://www.redaxo.org/
servername: REDAXO
error_email: null
fileperm: '0664'
dirperm: '0775'
session_duration: 7200
lang: de_de
use_gzip: true
use_etag: true
use_last_modified: false
start_page: structure
timezone: Europe/Berlin
socket_proxy: null
setup_addons:
    - backup
    - be_style
system_addons:
    - backup
    - mediapool
    - structure
    - metainfo
    - be_style
    - media_manager
    - users
    - install
table_prefix: rex_
temp_prefix: tmp_
db:
    1:
        host: localhost
        login: root
        password: ''
        name: redaxo_5_0
        persistent: false
    2:
        host: ''
        login: ''
        password: ''
        name: ''
        persistent: false
use_accesskeys: true
accesskeys:
    save: s
    apply: x
    delete: d
    add: a
    add_2: y
    logout: l
