# Dependabot config reference https://dependabot.com/docs/config-file/

version: 1
update_configs:
    - package_manager: "php:composer"
      directory: "/redaxo/src/addons/phpmailer"
      update_schedule: "live"
    - package_manager: "php:composer"
      directory: "/redaxo/src/addons/tests"
      update_schedule: "live"
    - package_manager: "php:composer"
      directory: "/redaxo/src/core"
      update_schedule: "live"
