name: PHP Checks

on:
    push:
        branches:
            - master
            - bugfix
            - temp
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches:
            - '*'

jobs:

    phpunit:
        name: unit tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
              include:
                  - php-version: '7.3'
                    db-image: 'mysql:5.6'
                  - php-version: '7.4'
                    db-image: 'mysql:5.7'
                  - php-version: '8.0'
                    db-image: 'mysql:8.0'
                  - php-version: '7.3'
                    db-image: 'mariadb:10.1'
                  - php-version: '7.4'
                    db-image: 'mariadb:latest'
        if: "!contains(github.event.head_commit.message, '[ci skip]')"

# https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers
        services:
            mysql:
                image: ${{ matrix.db-image }}
                env:
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: intl
                  coverage: none # disable xdebug, pcov

            - name: "composer install --prefer-dist"
              uses: "ramsey/composer-install@v1"
              if: matrix.php-version != '8.0'
              with:
                  composer-options: "--ansi --prefer-dist"
            - name: "composer install --prefer-dist --ignore-platform-req=php"
              uses: "ramsey/composer-install@v1"
              if: matrix.php-version == '8.0'
              with:
                  composer-options: "--ansi --prefer-dist --ignore-platform-req=php"

            - name: Setup Problem Matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Setup database
              run: |
                  mysql -uroot -h127.0.0.1 -proot -e 'create database redaxo5;'
                  git apply .github/workflows/default.config.yml.github-action.diff
            - run: |
                  php .tools/bin/setup
                  redaxo/bin/console system:report
            - run: |
                  vendor/bin/phpunit --colors=always
