name: PHP Checks

on:
    push:
        branches:
            - master
            - bugfix
            - temp
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches:
            - '*'

jobs:

    phpunit:
        name: unit tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
              redaxo-version: ${{ github.event.pull_request.head.sha }}
              php-version: ['7.3', '7.4', '8.0']
              db-image: ['mysql:5.7'] # a docker-hub key
              include:
                  - php-version: '7.4'
                    db-image: 'mysql:8.0'
                  - php-version: '7.3'
                    db-image: 'mariadb:10.1'
                  - php-version: '7.4'
                    db-image: 'mariadb:latest'

        if: "!contains(github.event.head_commit.message, '[ci skip]')"

# https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers
        services:
            mysql:
                image: ${{ matrix.db-image }}
                ports:
                    - 3306
        steps:
            - uses: actions/checkout@v2
              ref: ${{ matrix.redaxo-version }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: intl
                  coverage: none # disable xdebug, pcov

            - name: "composer install --prefer-dist"
              uses: "ramsey/composer-install@v1"
              if: matrix.php-version != '8.0'
              with:
                  composer-options: "--ansi --prefer-dist"
            - name: "composer install --prefer-dist --ignore-platform-reqs"
              uses: "ramsey/composer-install@v1"
              if: matrix.php-version == '8.0'
              with:
                  composer-options: "--ansi --prefer-dist --ignore-platform-reqs"

            - name: Setup Problem Matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - run: |
                  sudo /etc/init.d/mysql start
                  mysql -uroot -h127.0.0.1 -proot -e 'create database redaxo5;'
                  git apply .github/workflows/default.config.yml.github-action.diff
            - run: |
                  php .tools/bin/setup
            - run: |
                  vendor/bin/phpunit --colors=always
